### ISSUE TITLE
Add proper group and user pages with dynamic URLs

### ISSUE THREAD

**Issue by simp4t7** [simp4t7/the_movie_system#15]
@ptmphuong this is something you mentioned wanting to work on and I think it will help the front-end come together with better cohesion if we do this.

Now, is sort of the time to think about design while making this change. We can keep it messy in appearance, but what we need to think about is the information contained and on display.

So, what needs to be on the groups page? And what needs to be on the user profile pages? Do we already have everything we need or are there more systems that need to be implemented first to get the info we need for complete pages?

This is a pretty big change, so I could use some feedback on what we first need to make this happen. Do note that I still think it's too early to worry about the appearance, but consider the structure first and think about what information we need that we don't have yet.

**Comment by simp4t7** [comment]
This seems totally done, going to close this and you can open another for user URLs. Good job, thanks.

**Comment by simp4t7** [comment]
Thought this was just for groups, so reopening since it's for users too which isn't done.

**Comment by ptmphuong** [comment]
`/user/{userID}` works now.

For now we will need to just key in the user ID.  This is essentially the current `/all_groups`.
Eventually, I would want to replace `/all_groups` entirely, and just have `/user/userID` instead.

The problem now is after the user's logged in, we save their username in local storage, which is not neccessary.
After logging in, the login page should redirect/send the user to `/user/{userID}` directly.

Opening a new issue (#66) and I can look into it
